# Travis CI config

language: node_js
node_js:
  - 12

cache: npm

install: npm install

script:
  - npm run build
  - npm test

before_deploy:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  provider: script
  script: cicd/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    tags: true
