# Travis CI config

language: node_js
node_js:
  - 8

cache:
  - yarn
  - directories:
    - node_modules
    - $HOME/.local

install: yarn install

script:
  - yarn run build
  - yarn test

before_deploy:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  provider: script
  script: cicd/deploy.sh
  skip_cleanup: true
  on:
    branch: master
