# CI workflow

name: CI

on: [ push, pull_request ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test
      env:
        CI: true
